apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nginx-ingress
 namespace: api
 annotations:
  kubernetes.io/ingress.class: "nginx"
spec:
 ingressClassName: nginx
 tls:
 - hosts:
   - <your-domain-name>
   secretName: <your-secret>
 rules:
  - host: <your-domain-name>
    http:
     paths:
     - path: /app1
       pathType: Prefix
       backend:
        service:
         name: app1-service
         port:
          number: 80
  - host: <your-domain-name>
    http:
     paths:
     - path: /app2
       pathType: Prefix
       backend:
        service:
         name: app2-service
         port:
          number: 80
 
    
