apiVersion: v1
kind: PersistentVolume
metadata:
 name: nfs-app
 namespace: api
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteMany
 nfs:
  path: /opt/share
  server: 192.168.89.213
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-nfs-app
 namespace: api
spec:
 accessModes:
  - ReadWriteMany
 storageClassName: manual
 resources:
  requests:
   storage: 500Mi
    
